name: Extract and Release

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "ROM_URL"
        default: "ota.azureedge.net/OS1.0.2.0.UMFIDXM/miui_ARISTOTLEIDGlobal_OS1.0.2.0.UMFIDXM_b9ccc74619_14.0.zip"
      DEVICE_NAME:
        description: "DEVICE_NAME"
        default: "aristotle"
      EXTRACTED_FILES:
        description: "EXTRACTED_FILES"
        default: "boot.img, dtbo.img, product.img, system.img, system_ext.img"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download file
        run: curl -LJO ${{ github.event.inputs.ROM_URL }}

      - name: Extract Payload
        run: |
          chmod u+x .github/scripts/android-ota-extractor
          .github/scripts/android-ota-extractor *.zip
          echo -e "\n\e[31mDeleting files larger than 2GB...\e[0m"
          find . -maxdepth 1 -type f -size +2G -print -delete
          echo "ZIP_FILE=$(basename -a *.zip)" >> $GITHUB_ENV
          echo "ZIP_FILE_SHA256=$(sha256sum *.zip | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.inputs.EXTRACTED_FILES }}
          name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Device: ${{ github.event.inputs.DEVICE_NAME }}
            Filename: [${{ env.ZIP_FILE }}](${{ github.event.inputs.ROM_URL }})
            Extracted files: ${{ github.event.inputs.EXTRACTED_FILES }}
            SHA256: ${{ env.ZIP_FILE_SHA256 }}
